import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Chat from "@/components/Chat";

export const metadata = {
  title: "Adam Silvia Consulting | AI-Powered Authority Builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-segoe antialiased">
        <Navbar/>
        {children}
        <Footer/>
        <Chat/>
      </body>
    </html>
  );
}
